# Generated by Django 2.0.7 on 2018-07-10 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('zero_to_sixty', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('hp_rpm', models.IntegerField()),
                ('torque', models.IntegerField()),
                ('torque_rpm', models.IntegerField()),
                ('cylinders', models.IntegerField()),
                ('displacement', models.DecimalField(decimal_places=2, max_digits=4)),
                ('front_diameter', models.DecimalField(decimal_places=2, max_digits=4)),
                ('front_width', models.DecimalField(decimal_places=2, max_digits=4)),
                ('front_tire', models.CharField(max_length=12)),
                ('rear_diameter', models.DecimalField(decimal_places=2, max_digits=4)),
                ('rear_width', models.DecimalField(decimal_places=2, max_digits=4)),
                ('rear_tire', models.CharField(max_length=12)),
                ('length', models.DecimalField(decimal_places=2, max_digits=4)),
                ('width', models.DecimalField(decimal_places=2, max_digits=4)),
                ('height', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_rel', to='scraper.Make')),
            ],
        ),
        migrations.AddField(
            model_name='carmodel',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_model_rel', to='scraper.Make'),
        ),
        migrations.AddField(
            model_name='car',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_rel', to='scraper.Make'),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_rel', to='scraper.CarModel'),
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_rel', to='scraper.Year'),
        ),
    ]
